<p class="copy">
	Arks are the largest, heaviest, and strangest starships humanity has ever produced, though to call them ships is underselling them, as several Arks are fully fledged states in their own right. No two Arks are alike, and the journey to becoming an Ark is a strange one that, in some cases, has played out over more than half a century. Only two of the six extant Arks were purpose-built; the rest were accidents of construction. Stations, <?php echo sf_lore_link('stellar-carriers', 'stellar carriers'); ?>, and even an asteroid colony have formed the core of an Ark. From there, the process is simple but absurd: take that original core and grow it with modules and additions far beyond its original designed capacity. Keep adding until nothing of the original vessel remains and you're left with something wholly new and unique.
</p>
<p class="copy">
	Arks are Frankenstein constructions of space station, flotilla, and starship, endlessly growing as their economic might and importance in the settled systems grows. New habitation modules are bolted on, ships anchor for the final time and become yet one more piece of the Ark, and infill is laid wherever space can be found. New bulkheads are installed, and the whole endeavor is kept structurally sound with a latticework of supports, wiring, and piping. Each Ark has its own culture and politics, with hundreds of thousands of residents at the low end and millions being the norm.
</p>
<p class="copy">
	Arks act as floating cities, with several of them on decades-long rotations between settled systems. Each is capable of berthing fleets of ships and storing millions of tons of cargo. Interstellar travel on an Ark is by far the safest and most comfortable way to transit between stars. Arks feature their own food production facilities, huge numbers of <?php echo sf_lore_link('switch-gates', 'Switch Gates'); ?>, and more than enough expert personnel to solve whatever problems arise. Most also sport defense fleets of their own, making them formidable targets even for some nations. What they are not, however, is fast. If you're taking an Ark to the next system, be prepared for a long stay.
</p>
